// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypmtcuqbndkcezjupwxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwbXRjdXFibmRrY2V6anVwd3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTgxOTQsImV4cCI6MjA1MTQ5NDE5NH0.5s3RaezB_krlNoqDK3QvskZpNr-gkg1SE_BomoQlLbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);