// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktkeayxnlfyhalctgfot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0a2VheXhubGZ5aGFsY3RnZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NzIyMDAsImV4cCI6MjA1MTI0ODIwMH0.D5uJ4g4qm58qDy-sBZiZiUwv_kWj9i3GOATUSfvi3P8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);